### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by sando0710** [sando0710/furima-28896#13]
### フリマURL
https://furima-28896.herokuapp.com
### Basic認証のIDとパスワード
ID: admin
パスワード：2222
### 出品者用のメールアドレスとパスワード
メールアドレス：sandoumasahito@gmail.com
パスワード：g1356135
### 購入者用のメールアドレスとパスワード
メールアドレス：12345678@gmail.com
パスワード:abcd0710
### 購入用カードの番号・期限・セキュリティコード
番号：4242424242424242
期限：3月 23年
セキュリティーコード：123
### よろしくお願いいたします。

**Comment by tech-oa** [comment]
sando0710さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
○Basic認証が実装されていません。

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by sando0710** [comment]
### Basic認証のIDとパスワード
ID: admin
パスワード：2222

## 上記の箇所を修正しました。確認願います。

**Comment by tech-oa** [comment]
sando0710さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
